name: GarysTestSite
favicon: null
layout_spectrum: 0.20372924022376537
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#733795'
    - '#ffffff'
    - '#0000ff'
    - '#ff00ff'
  brandStrength: 0.5
  lightness: 0.911788476165384
  saturation: 0.9602612138260156
  rhythmicContrast: 0.9180777727160603
purpose: []
